import { db, initSchema } from "./db.js";

initSchema();

const categories = [
  { slug: "emergency", name_ar: "طوارئ وخدمات حكومية" },
  { slug: "mobile-internet", name_ar: "خدمات المحمول والإنترنت" },
  { slug: "banks", name_ar: "البنوك" },
  { slug: "finance-payments", name_ar: "شركات التمويل والدفع الإلكتروني" },
  { slug: "hospitals", name_ar: "المستشفيات والمراكز الطبية" },
  { slug: "labs", name_ar: "معامل التحاليل والأشعة" },
  { slug: "pharmacies", name_ar: "صيدليات" },
  { slug: "auto-service", name_ar: "توكيلات وصيانة السيارات" },
  { slug: "shipping", name_ar: "شركات الشحن والنقل" },
  { slug: "restaurants", name_ar: "المطاعم" },
  { slug: "cafes-desserts", name_ar: "كافيهات وحلويات" },
  { slug: "supermarkets", name_ar: "سوبر ماركت ومولات" },
  { slug: "hotels", name_ar: "فنادق" },
  { slug: "appliances", name_ar: "أجهزة منزلية وصيانة" },
  { slug: "furniture", name_ar: "أثاث ومفروشات" },
  { slug: "realestate", name_ar: "مطورين عقاريين" },
  { slug: "apps", name_ar: "تطبيقات وخدمات إلكترونية" },
  { slug: "charity", name_ar: "جمعيات خيرية" },
  { slug: "syndicates", name_ar: "نقابات مهنية" },
  { slug: "education", name_ar: "جامعات ومؤسسات تعليمية" },
  { slug: "airlines", name_ar: "شركات الطيران والسياحة" }
];

const contacts = [
  // طوارئ
  ["emergency", "وزارة الصحة (الإمداد الطبي / الطوارئ)", "137"],
  ["emergency", "هيئة الإسعاف المصرية", "123"],
  ["emergency", "شرطة النجدة", "122"],
  ["emergency", "المطافئ / الحماية المدنية", "180"],
  ["emergency", "طوارئ الكهرباء", "121"],
  ["emergency", "طوارئ الغاز الطبيعي (تاون جاس)", "129"],
  ["emergency", "طوارئ المياه والصرف الصحي", "125"],
  ["emergency", "جهاز حماية المستهلك", "19588"],
  ["emergency", "خط نجدة الطفل", "16000"],
  ["emergency", "مكافحة جرائم الإنترنت", "108"],
  ["emergency", "هيئة التأمين الصحي الشامل", "15344"],
  ["emergency", "صندوق مكافحة وعلاج الإدمان", "16023"],
  ["emergency", "منظومة الشكاوى الحكومية الموحدة", "16528"],
  ["emergency", "دار الإفتاء المصرية", "107"],
  ["emergency", "الهيئة القومية للتأمينات الاجتماعية", "16217"],
  ["emergency", "الإدارة العامة للمرور", "128"],
  ["emergency", "مصلحة الضرائب المصرية", "16395"],
  ["emergency", "الخط الساخن للسياحة والآثار", "19654"],
  ["emergency", "وزارة التموين والتجارة الداخلية", "16280"],
  ["emergency", "جهاز تنمية المشروعات", "16733"],
  ["emergency", "هيئة الرقابة الإدارية", "16100"],
  ["emergency", "برنامج تكافل وكرامة", "19680"],
  ["emergency", "صندوق الإسكان الاجتماعي", "1188"],
  ["emergency", "هيئة المجتمعات العمرانية الجديدة", "15100"],
  ["emergency", "وزارة التربية والتعليم", "19368"],
  ["emergency", "بوابة العمرة المصرية", "19385"],
  // موبيل وإنترنت
  ["mobile-internet", "المصرية للاتصالات WE (من أي رقم WE)", "111"],
  ["mobile-internet", "المصرية للاتصالات WE (من أي شبكة أخرى)", "01555000111"],
  ["mobile-internet", "فودافون مصر (خدمة العملاء الموحدة)", "16888"],
  ["mobile-internet", "أورانج مصر", "16110"],
  ["mobile-internet", "أورانج إنترنت منزلي", "16333"],
  ["mobile-internet", "اتصالات مصر", "333"],
  ["mobile-internet", "اتصالات إنترنت منزلي", "16511"],
  // بنوك
  ["banks", "البنك الأهلي المصري", "19623"],
  ["banks", "بنك مصر", "19888"],
  ["banks", "البنك التجاري الدولي CIB", "19666"],
  ["banks", "بنك الإسكندرية", "19033"],
  ["banks", "بنك QNB الأهلي", "19700"],
  ["banks", "بنك القاهرة", "16990"],
  ["banks", "بنك كريدي أجريكول", "19191"],
  ["banks", "بنك الكويت الوطني NBK", "19336"],
  ["banks", "البنك المصري الخليجي EGBank", "19342"],
  ["banks", "بنك التعمير والإسكان", "19995"],
  ["banks", "بنك فيصل الإسلامي", "19851"],
  ["banks", "مصرف أبوظبي الإسلامي ADIB", "19951"],
  ["banks", "البنك العربي", "19100"],
  ["banks", "بنك الإمارات دبي الوطني", "16664"],
  ["banks", "بنك أبوظبي الأول FABMISR", "16607"],
  ["banks", "بنك المشرق", "19677"],
  ["banks", "البنك الأهلي المتحد", "19072"],
  ["banks", "بنك البركة", "19373"],
  ["banks", "بنك SAIB", "16668"],
  ["banks", "ميد بنك MIDBANK", "19121"],
  ["banks", "التجاري وفا بنك", "16222"],
  // تمويل ودفع
  ["finance-payments", "فاليو للتقسيط", "16671"],
  ["finance-payments", "كونتاكت للتمويل", "16177"],
  ["finance-payments", "أمان للخدمات المالية", "19910"],
  ["finance-payments", "سهولة للتقسيط", "16032"],
  ["finance-payments", "بريميوم كارد", "16818"],
  ["finance-payments", "فوري Fawry", "19016"],
  ["finance-payments", "بي Bee للدفع الإلكتروني", "16233"],
  ["finance-payments", "مصاري Masary", "16994"],
  // مستشفيات
  ["hospitals", "مستشفى وادي النيل", "16444"],
  ["hospitals", "مستشفى العربي", "16108"],
  ["hospitals", "مستشفى النيل بدراوي", "16422"],
  ["hospitals", "مستشفى دار الفؤاد", "16370"],
  ["hospitals", "مستشفى السعودي الألماني", "16259"],
  ["hospitals", "مستشفيات كليوباترا", "19668 / 19005"],
  ["hospitals", "مستشفى مبرة العصافرة", "15016"],
  ["hospitals", "مستشفيات أندلسية", "16781"],
  ["hospitals", "مستشفى رفيدة Rofayda", "16677"],
  ["hospitals", "مستشفيات مغربي للعيون", "16070"],
  ["hospitals", "مستشفى شفاء الأورمان", "19455"],
  ["hospitals", "مستشفى أيادي المستقبل", "16034"],
  ["hospitals", "معهد القلب القومي", "16419"],
  ["hospitals", "مستشفى النور للعيون", "16052"],
  ["hospitals", "مستشفى السلام الدولي", "19885"],
  ["hospitals", "مستشفى النزهة الدولي", "19086"],
  ["hospitals", "المستشفى الجوي التخصصي", "19448"],
  ["hospitals", "مستشفى ابن سينا", "16205"],
  ["hospitals", "مستشفى الأمل", "16271"],
  ["hospitals", "مستشفى بهية", "16602"],
  ["hospitals", "مستشفى أهل مصر", "16866"],
  ["hospitals", "مؤسسة مجدي يعقوب", "19731"],
  ["hospitals", "مستشفى سرطان الأطفال 57357", "19057"],
  ["hospitals", "مستشفى زايد التخصصي", "19062"],
  ["hospitals", "مستشفى دار الشفاء", "16258"],
  ["hospitals", "مستشفى عين شمس التخصصي", "16303"],
  ["hospitals", "مستشفى الصفا", "16181"],
  // معامل
  ["labs", "معامل المختبر", "19014"],
  ["labs", "معامل البرج", "19044"],
  ["labs", "كايرو سكان للأشعة", "19144"],
  ["labs", "معامل مبرة العصافرة", "19605"],
  ["labs", "معامل رويال لاب", "16522"],
  ["labs", "معامل حسب Hassab", "19566"],
  ["labs", "تكنو سكان", "19330"],
  ["labs", "معامل الشمس", "16538"],
  ["labs", "معامل ساريدار", "19175"],
  ["labs", "معامل ألفا", "16181"],
  // صيدليات
  ["pharmacies", "العزبي", "19600"],
  ["pharmacies", "سيف", "19304"],
  ["pharmacies", "دلمار وعطالله", "19955"],
  ["pharmacies", "كير", "16416"],
  ["pharmacies", "علي وعلي", "19905"],
  ["pharmacies", "مصر", "19110"],
  ["pharmacies", "رشدي", "19661"],
  ["pharmacies", "الطرشاوي", "19101"],
  ["pharmacies", "الإسعاف", "16682"],
  ["pharmacies", "نورماندي", "19688"],
  ["pharmacies", "خليل", "16182"],
  ["pharmacies", "الطيبي", "19747"],
  ["pharmacies", "بلبع", "16738"],
  ["pharmacies", "عز الدين", "16080"],
  ["pharmacies", "محفوظ", "19045"],
  ["pharmacies", "عابدين", "19828"],
  ["pharmacies", "الأجزخانة", "16445"],
  ["pharmacies", "فودة", "19325"],
  ["pharmacies", "طارق", "19416"],
  ["pharmacies", "أبو علي", "19630"],
  // سيارات
  ["auto-service", "مانسكو (بيجو)", "16674"],
  ["auto-service", "أبو غالي موتورز (سوبارو / جيلي)", "19570"],
  ["auto-service", "تويوتا مصر", "16550"],
  ["auto-service", "منصور للسيارات (شيفروليه / أوبل / MG)", "16424"],
  ["auto-service", "غبور أوتو (هيونداي / شيري)", "16661"],
  ["auto-service", "كيا إيجيبت EIT", "19542"],
  ["auto-service", "نيسان موتور إيجيبت", "16244"],
  ["auto-service", "عز العرب (فولفو)", "19399"],
  ["auto-service", "رينو مصر", "16202"],
  ["auto-service", "سكودا مصر", "16555"],
  ["auto-service", "فولكس فاجن وأودي", "19525"],
  ["auto-service", "هوندا مصر", "19811"],
  ["auto-service", "مرسيدس بنز مصر", "16500"],
  ["auto-service", "بي إم دبليو BMW", "19269"],
  ["auto-service", "ميتسوبيشي", "16606"],
  ["auto-service", "داينامكس (فيات)", "16288"],
  ["auto-service", "القصراوي جروب (جاك / جيتور)", "16406"],
  // شحن
  ["shipping", "سكك حديد مصر", "15047"],
  ["shipping", "جو باص", "19567"],
  ["shipping", "سوبر جيت", "19157"],
  ["shipping", "بلو باص", "16128"],
  ["shipping", "مواصلات مصر", "19982"],
  ["shipping", "سويفل Swvl", "19818"],
  ["shipping", "أرامكس Aramex", "16996"],
  ["shipping", "دي إتش إل DHL", "16345"],
  ["shipping", "فيديكس إكسبريس", "19985"],
  ["shipping", "بوسطة مصر Bosta", "19043"],
  ["shipping", "مايلرز للشحن Mylerz", "19902"],
  // مطاعم
  ["restaurants", "ماكدونالدز", "19997"],
  ["restaurants", "كنتاكي KFC", "19019"],
  ["restaurants", "هارديز", "19066"],
  ["restaurants", "كوك دور", "16999"],
  ["restaurants", "بافلو برجر", "19914"],
  ["restaurants", "برجر كينج", "16977"],
  ["restaurants", "بازوكا", "16455"],
  ["restaurants", "هارتاك", "15428"],
  ["restaurants", "مؤمن", "16600"],
  ["restaurants", "ديسوقي أند صودا", "16225"],
  ["restaurants", "ويليز كيتشن", "19256"],
  ["restaurants", "دجاج تكا", "19099"],
  ["restaurants", "بيتزا هت", "19000"],
  ["restaurants", "دومينوز بيتزا", "19223"],
  ["restaurants", "بابا جونز", "19277"],
  ["restaurants", "أبو عمار السوري", "19296"],
  ["restaurants", "ابن الشام", "19286"],
  ["restaurants", "شاورما الريم", "16435"],
  ["restaurants", "أنس الدمشقي", "16206"],
  ["restaurants", "أسماك Asmak", "16906"],
  ["restaurants", "جندوفلي", "16669"],
  ["restaurants", "سبكترا", "19491"],
  ["restaurants", "كريف Crave", "16446"],
  ["restaurants", "بريموز بيتزا", "19414"],
  ["restaurants", "بريجو Prego", "16121"],
  ["restaurants", "صبحي كابر", "16640"],
  ["restaurants", "أبو شقرة", "19090"],
  ["restaurants", "الدهان", "16194"],
  ["restaurants", "كشري التحرير", "16972"],
  ["restaurants", "كشري أبو طارق", "16011"],
  ["restaurants", "قرية بلبع (الإسكندرية)", "16941"],
  ["restaurants", "طبالي", "19061"],
  ["restaurants", "كشري سيد حنفي", "16959"],
  ["restaurants", "عز المنوفي", "16976"],
  ["restaurants", "مطاعم جاد", "16475"],
  ["restaurants", "كبابجي الأزهر فرحات", "16773"],
  ["restaurants", "حضرموت عنتر", "15280"],
  // كافيهات وحلويات
  ["cafes-desserts", "حلواني العبد", "16437"],
  ["cafes-desserts", "لابوار La Poire", "19515"],
  ["cafes-desserts", "تسيباس", "16944"],
  ["cafes-desserts", "سيلانترو", "16949"],
  ["cafes-desserts", "ستاربكس مصر", "19206"],
  ["cafes-desserts", "حلواني إيتوال", "16909"],
  ["cafes-desserts", "حلواني الصعيدي", "19273"],
  ["cafes-desserts", "ساليه سوكريه", "19632"],
  ["cafes-desserts", "مونجيني", "19555"],
  ["cafes-desserts", "المخبز TBS", "16659"],
  ["cafes-desserts", "بينوس كافيه", "16938"],
  ["cafes-desserts", "كوستا كافيه", "16933"],
  ["cafes-desserts", "نولا كب كيك", "16714"],
  // سوبر ماركت
  ["supermarkets", "كارفور", "16061"],
  ["supermarkets", "هايبر وان", "16400"],
  ["supermarkets", "فتح الله ماركت", "16069"],
  ["supermarkets", "سعودي ماركت", "16116"],
  ["supermarkets", "كازيون", "19609"],
  ["supermarkets", "خير زمان", "16007"],
  ["supermarkets", "مترو ماركت", "16055"],
  ["supermarkets", "ألفا ماركت", "16120"],
  ["supermarkets", "أسواق العثيم", "19279"],
  ["supermarkets", "بيم ماركت BIM", "16942"],
  ["supermarkets", "أسواق المحلاوي", "16073"],
  ["supermarkets", "زهران ماركت", "16115"],
  ["supermarkets", "بيت الجملة", "16568"],
  ["supermarkets", "أوسكار جراند ستورز", "16388"],
  ["supermarkets", "جورميه", "19339"],
  ["supermarkets", "سبينيس", "16005"],
  ["supermarkets", "كايرو فيستيفال سيتي مول", "16367"],
  ["supermarkets", "داندي ميجا مول", "19553"],
  ["supermarkets", "مول العرب", "16557"],
  ["supermarkets", "مول مصر", "16255"],
  ["supermarkets", "هوم سنتر / ماكس / سنتربوينت / محل الأطفال", "16935"],
  // فنادق
  ["hotels", "ماريوت", "16555"],
  ["hotels", "هيلتون", "19009"],
  ["hotels", "فورسيزونز", "19779"],
  ["hotels", "شتيجنبرجر", "16084"],
  ["hotels", "توليب", "16056"],
  ["hotels", "ريكسوس", "16988"],
  ["hotels", "صن رايز", "16032"],
  ["hotels", "بيك ألباتروس", "15788"],
  ["hotels", "راديسون بلو", "16203"],
  // أجهزة منزلية
  ["appliances", "إل جي LG", "19960"],
  ["appliances", "سامسونج", "16580"],
  ["appliances", "بوش Bosch", "15196"],
  ["appliances", "زانوسي", "19999"],
  ["appliances", "العربي جروب (توشيبا / تورنيدو)", "19319"],
  ["appliances", "فريش", "19059"],
  ["appliances", "كريازي", "19092"],
  ["appliances", "يونيون إير", "19012"],
  ["appliances", "بيكو", "16165"],
  ["appliances", "وايت ويل", "19118"],
  ["appliances", "كاريير", "16111"],
  ["appliances", "هوفر", "19319"],
  ["appliances", "تريد لاين ستورز (أبل)", "19857"],
  ["appliances", "راديو شاك", "19419"],
  ["appliances", "القاهرة للمبيعات", "19146"],
  // أثاث
  ["furniture", "إيكيا مصر", "16581"],
  ["furniture", "قباني للأثاث", "19064"],
  ["furniture", "رنين", "16113"],
  ["furniture", "إن آند آوت", "19258"],
  ["furniture", "أشلي", "19213"],
  ["furniture", "هب فرنتشر", "15135"],
  ["furniture", "النساجون الشرقيون", "16074"],
  ["furniture", "مفكو حلوان", "19026"],
  ["furniture", "سمارت فرنتشر", "16944"],
  ["furniture", "المرشدي", "16901"],
  // مطورين عقاريين
  ["realestate", "طلعت مصطفى TMG", "19691"],
  ["realestate", "ماونتن فيو", "16201"],
  ["realestate", "سوديك", "16220"],
  ["realestate", "بالم هيلز", "19742"],
  ["realestate", "أورا ديفلوبرز", "16221"],
  ["realestate", "إعمار مصر", "16116"],
  ["realestate", "تطوير مصر", "16094"],
  ["realestate", "أوراسكوم للتنمية", "16222"],
  ["realestate", "مصر إيطاليا", "16519"],
  ["realestate", "بورتو جروب", "19106"],
  ["realestate", "مدينة نصر للإسكان MNHD", "16559"],
  ["realestate", "هايد بارك", "16231"],
  ["realestate", "الأهلي صبور", "16141"],
  ["realestate", "مراكز Marakez", "16226"],
  ["realestate", "كليوباترا العقارية", "16668"],
  ["realestate", "حسن علام العقارية", "16302"],
  // تطبيقات وخدمات
  ["apps", "طلبات Talabat", "19622"],
  ["apps", "المنيوز Elmenus", "16899"],
  ["apps", "وفرها Waffarha", "16457"],
  ["apps", "أوليكس / دوبيزل", "16012"],
  ["apps", "انستاشوب", "16148"],
  ["apps", "بريمور", "16936"],
  ["apps", "مكاسب Makaseb", "16533"],
  ["apps", "فيزيتا Vezeeta", "16676"],
  ["apps", "ياسير Yassir", "16611"],
  // جمعيات خيرية
  ["charity", "بنك الطعام المصري", "16060"],
  ["charity", "رسالة", "19450"],
  ["charity", "مصر الخير", "16140"],
  ["charity", "الأورمان", "19455"],
  ["charity", "بيت الزكاة والصدقات", "15111"],
  ["charity", "صناع الحياة", "16563"],
  ["charity", "مرسال", "15458"],
  // نقابات
  ["syndicates", "المهندسين", "19451"],
  ["syndicates", "الأطباء (النقابة العامة بالقاهرة)", "0223636366 / 01095111247"],
  ["syndicates", "المحامين", "19712"],
  ["syndicates", "التجاريين", "19452"],
  // تعليم
  ["education", "الجامعة الأمريكية بالقاهرة (AUC)", "19282"],
  ["education", "الجامعة البريطانية في مصر (BUE)", "19283"],
  ["education", "الجامعة الألمانية بالقاهرة (GUC)", "16482"],
  ["education", "جامعة مصر للعلوم والتكنولوجيا (MUST)", "16878"],
  ["education", "المجلس الأعلى للجامعات", "0235738583 / 0235716348"],
  // طيران
  ["airlines", "مصر للطيران EgyptAir", "1717 / 090070000"],
  ["airlines", "النيل للطيران Nile Air", "19415"]
];

function importData() {
  const tx = db.transaction(() => {
    db.prepare("DELETE FROM contacts").run();
    db.prepare("DELETE FROM categories").run();
    db.prepare("DELETE FROM sqlite_sequence WHERE name IN ('contacts','categories')").run();

    const insCat = db.prepare("INSERT INTO categories (slug, name_ar) VALUES (@slug, @name_ar)");
    categories.forEach((c) => insCat.run(c));

    const catMap = new Map(db.prepare("SELECT slug, id FROM categories").all().map((c) => [c.slug, c.id]));
    const insContact = db.prepare(
      `INSERT INTO contacts (name_ar, phone, category_id, governorate_id, is_non_phone)
       VALUES (@name_ar, @phone, @category_id, NULL, 0)`
    );
    contacts.forEach(([slug, name, phone]) => {
      const category_id = catMap.get(slug);
      if (!category_id) return;
      insContact.run({ name_ar: name, phone: String(phone), category_id });
    });
  });

  tx();
  console.log(`Imported ${categories.length} categories and ${contacts.length} contacts`);
}

importData();
